name: "Vprofile IAC"
on:
  push:
    branches:
      - main
      - stage
    paths:
      - terraform/**  
  pull_request:
    branches:
      - main
      - stage
    paths:
      - terraform/**

env:   
  #Credentials for deployment to AWS   
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}      

  #S3 bucket for Terraform state
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
  AWS_REGION: us-east-1
  EKS_CLUSTER: vprofile-eks

jobs:
  terraform:  
    name: "Apply Terraform code chnages"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4    

      - name: Setup Terraform with specific version on the runner
        uses: hashicorp/setup-terraform@v2
        
      - name: Terraform Init
        id: terraform_init
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"

      - name: Terraform format
        id: fmt
        run: terraform fmt -check  

      - name: Terraform validate
        id: validate
        run: terraform validate  
      
      - name: Terraform plan
        id: plan    
        run: terraform plan -no-color -out=tfplan -input=false   
        continue-on-error: true

      - name: Terraform plan status
        if: steps.plan.outcome =='failure'
        run: exit 1


##        

